nama = input("Masukan nama anda : ")
usia = input("Masukan usia anda : ")
alamat = input("Masukan alamat asli anda : ")
f = open("datadiri.txt","a")
f.write (f"HALO {nama}")
f.write(f"\nusia anda : {usia}")
f.write(f"\nalamat anda : {alamat}")
f.write(30*"=")
f = open("datadiri.txt","r")
print(f.read())
f.close()
