# Generated by Django 4.2.1 on 2023-06-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='username',
            new_name='user',
        ),
    ]
